name: Tests
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'
jobs:
  tests:
    name: Lint with R and Python ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python: ['3.10', '3.9', '3.8']
    defaults:
      run:
        # Enable the conda environment via ~/.bashrc and ~/.profile
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Cache conda
        uses: actions/cache@v4
        env:
          # Increase this value to reset cache if laava.conda_env.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('laava.conda_env.yml') }}
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: AAV.env
          auto-activate-base: false
          auto-update-conda: true
          channel-priority: strict
          environment-file: laava.conda_env.yml
          python-version: ${{ matrix.python }}
          use-only-tar-bz2: true  # Required for caching
      - name: Show conda environment
        run: |
          conda info
          conda list
      - name: Lint Python scripts
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Lint R script
        run: |
          Rscript -e 'library(lintr); options(lintr.error_on_lint=TRUE); lint_dir(".", linters=linters_with_tags("correctness"))'
